# coding: utf-8

# flake8: noqa
"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.134
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from tpdk.models.address import Address
from tpdk.models.address_independent_write import AddressIndependentWrite
from tpdk.models.address_update import AddressUpdate
from tpdk.models.address_write import AddressWrite
from tpdk.models.api_client_post_creation_read import ApiClientPostCreationRead
from tpdk.models.api_client_read import ApiClientRead
from tpdk.models.api_client_write import ApiClientWrite
from tpdk.models.dispute_collection_read import DisputeCollectionRead
from tpdk.models.dispute_dispute_read import DisputeDisputeRead
from tpdk.models.dispute_independent_write import DisputeIndependentWrite
from tpdk.models.dispute_post_creation_read import DisputePostCreationRead
from tpdk.models.dispute_read import DisputeRead
from tpdk.models.dispute_update import DisputeUpdate
from tpdk.models.dispute_write import DisputeWrite
from tpdk.models.evaluation_read import EvaluationRead
from tpdk.models.evaluation_write import EvaluationWrite
from tpdk.models.evidence import Evidence
from tpdk.models.evidence_read import EvidenceRead
from tpdk.models.evidence_write import EvidenceWrite
from tpdk.models.media import Media
from tpdk.models.media_authenticated_read import MediaAuthenticatedRead
from tpdk.models.media_collection_read import MediaCollectionRead
from tpdk.models.media_dispute_read import MediaDisputeRead
from tpdk.models.media_read import MediaRead
from tpdk.models.metadata import Metadata
from tpdk.models.metadata_dispute_read import MetadataDisputeRead
from tpdk.models.metadata_independent_write import MetadataIndependentWrite
from tpdk.models.metadata_read import MetadataRead
from tpdk.models.metadata_update import MetadataUpdate
from tpdk.models.metadata_write import MetadataWrite
from tpdk.models.notification_read import NotificationRead
from tpdk.models.notification_update import NotificationUpdate
from tpdk.models.offer import Offer
from tpdk.models.offer_collection_read import OfferCollectionRead
from tpdk.models.offer_dispute_read import OfferDisputeRead
from tpdk.models.offer_independent_write import OfferIndependentWrite
from tpdk.models.offer_post_creation_read import OfferPostCreationRead
from tpdk.models.offer_read import OfferRead
from tpdk.models.offer_update import OfferUpdate
from tpdk.models.offer_write import OfferWrite
from tpdk.models.organization_authenticated_read import OrganizationAuthenticatedRead
from tpdk.models.organization_collection_read import OrganizationCollectionRead
from tpdk.models.organization_dispute_read import OrganizationDisputeRead
from tpdk.models.organization_read import OrganizationRead
from tpdk.models.organization_update import OrganizationUpdate
from tpdk.models.organization_write import OrganizationWrite
from tpdk.models.parcel import Parcel
from tpdk.models.parcel_dispute_read import ParcelDisputeRead
from tpdk.models.parcel_independent_write import ParcelIndependentWrite
from tpdk.models.parcel_read import ParcelRead
from tpdk.models.parcel_write import ParcelWrite
from tpdk.models.persona import Persona
from tpdk.models.persona_auth_return import PersonaAuthReturn
from tpdk.models.persona_collection_read import PersonaCollectionRead
from tpdk.models.persona_dispute_read import PersonaDisputeRead
from tpdk.models.persona_external_auth import PersonaExternalAuth
from tpdk.models.persona_independent_write import PersonaIndependentWrite
from tpdk.models.persona_post_auth_read import PersonaPostAuthRead
from tpdk.models.persona_read import PersonaRead
from tpdk.models.persona_register import PersonaRegister
from tpdk.models.persona_token_write import PersonaTokenWrite
from tpdk.models.persona_update import PersonaUpdate
from tpdk.models.persona_write import PersonaWrite
from tpdk.models.transaction_collection_read import TransactionCollectionRead
from tpdk.models.transaction_dispute_read import TransactionDisputeRead
from tpdk.models.transaction_independent_write import TransactionIndependentWrite
from tpdk.models.transaction_read import TransactionRead
from tpdk.models.unprocessable_entity import UnprocessableEntity
from tpdk.models.unprocessable_entity_violations_inner import UnprocessableEntityViolationsInner
from tpdk.models.user import User
from tpdk.models.user_authenticated_read import UserAuthenticatedRead
from tpdk.models.user_collection_read import UserCollectionRead
from tpdk.models.user_email_validation_write import UserEmailValidationWrite
from tpdk.models.user_invite import UserInvite
from tpdk.models.user_post_register_read import UserPostRegisterRead
from tpdk.models.user_update import UserUpdate
from tpdk.models.user_write import UserWrite
from tpdk.models.view import View
from tpdk.models.view_dispute_read import ViewDisputeRead
from tpdk.models.view_read import ViewRead
from tpdk.models.webhook import Webhook
from tpdk.models.webhook_history_collection_read import WebhookHistoryCollectionRead
from tpdk.models.webhook_history_read import WebhookHistoryRead
from tpdk.models.webhook_object import WebhookObject
from tpdk.models.webhook_subscription_read import WebhookSubscriptionRead
from tpdk.models.webhook_subscription_write import WebhookSubscriptionWrite
from tpdk.models.workflow_event_dispute_read import WorkflowEventDisputeRead
from tpdk.models.workflow_event_read import WorkflowEventRead
