# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.179
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tpdk.models.evidence_read_media import EvidenceReadMedia

class TestEvidenceReadMedia(unittest.TestCase):
    """EvidenceReadMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvidenceReadMedia:
        """Test EvidenceReadMedia
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvidenceReadMedia`
        """
        model = EvidenceReadMedia()
        if include_optional:
            return EvidenceReadMedia(
                public_url = https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg
            )
        else:
            return EvidenceReadMedia(
                public_url = https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg,
        )
        """

    def testEvidenceReadMedia(self):
        """Test EvidenceReadMedia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
