# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.179
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tpdk.models.user_write_organization import UserWriteOrganization

class TestUserWriteOrganization(unittest.TestCase):
    """UserWriteOrganization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserWriteOrganization:
        """Test UserWriteOrganization
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserWriteOrganization`
        """
        model = UserWriteOrganization()
        if include_optional:
            return UserWriteOrganization(
                id = None,
                name = None,
                vat_number = None,
                commercial_registry_number = None,
                website_url = None,
                billing_address = None
            )
        else:
            return UserWriteOrganization(
                name = None,
                vat_number = None,
                commercial_registry_number = None,
        )
        """

    def testUserWriteOrganization(self):
        """Test UserWriteOrganization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
