# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.199
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tpdk.models.offer_collection_read import OfferCollectionRead

class TestOfferCollectionRead(unittest.TestCase):
    """OfferCollectionRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OfferCollectionRead:
        """Test OfferCollectionRead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OfferCollectionRead`
        """
        model = OfferCollectionRead()
        if include_optional:
            return OfferCollectionRead(
                ulid = '',
                public_url = 'https://marketplace.tld/offers/that-special-item-i-wish-to-sold',
                enforce_persona_auth = True,
                override_rate_commission_safe_checkout = 1.337,
                seller = 'https://example.com/',
                nature = 'physical_item',
                title = 'ASUS TUF X570-PLUS GAMING Motherboard',
                unit_price = 125.54,
                currency_code = 'EUR',
                item_count = 1,
                condition = 'USED',
                shipping_allowed = True,
                hand_delivery_allowed = True,
                shipping_carriers = [
                    'SwissPost'
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                iri = 'https://example.com/'
            )
        else:
            return OfferCollectionRead(
                ulid = '',
                enforce_persona_auth = True,
                seller = 'https://example.com/',
                nature = 'physical_item',
                shipping_allowed = True,
                hand_delivery_allowed = True,
        )
        """

    def testOfferCollectionRead(self):
        """Test OfferCollectionRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
