# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.  # noqa: E501

    The version of the OpenAPI document: 2.0.22
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import tpdk
from tpdk.api.branding_api import BrandingApi  # noqa: E501
from tpdk.rest import ApiException


class TestBrandingApi(unittest.TestCase):
    """BrandingApi unit test stubs"""

    def setUp(self):
        self.api = tpdk.api.branding_api.BrandingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_organizations_id_patch(self):
        """Test case for api_organizations_id_patch

        Update your Organization details, branding or parameters  # noqa: E501
        """
        pass

    def test_api_organizations_idicon_delete(self):
        """Test case for api_organizations_idicon_delete

        Unset your Organization Icon  # noqa: E501
        """
        pass

    def test_api_organizations_idicon_post(self):
        """Test case for api_organizations_idicon_post

        Upload your Organization Icon  # noqa: E501
        """
        pass

    def test_api_organizations_idlogo_delete(self):
        """Test case for api_organizations_idlogo_delete

        Unset your Organization Logo  # noqa: E501
        """
        pass

    def test_api_organizations_idlogo_post(self):
        """Test case for api_organizations_idlogo_post

        Upload your Organization logo  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
