# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.179
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tpdk.models.user_collection_read_organization import UserCollectionReadOrganization

class TestUserCollectionReadOrganization(unittest.TestCase):
    """UserCollectionReadOrganization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCollectionReadOrganization:
        """Test UserCollectionReadOrganization
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCollectionReadOrganization`
        """
        model = UserCollectionReadOrganization()
        if include_optional:
            return UserCollectionReadOrganization(
                id = None,
                name = None,
                vat_number = None,
                commercial_registry_number = None,
                website_url = None,
                icon = None,
                logo = None,
                direct_notification_toggle = true,
                safe_checkout_toggle = None,
                resolution_center_toggle = true,
                internal_messaging_toggle = true,
                persona_auth_portal_toggle = None,
                automated_return_toggle = true,
                counter_proposal_toggle = true,
                flat_rate_enabled = None,
                rate_commission_safe_checkout = None
            )
        else:
            return UserCollectionReadOrganization(
                direct_notification_toggle = true,
                safe_checkout_toggle = None,
                resolution_center_toggle = true,
                internal_messaging_toggle = true,
                persona_auth_portal_toggle = None,
                automated_return_toggle = true,
                counter_proposal_toggle = true,
                rate_commission_safe_checkout = None,
        )
        """

    def testUserCollectionReadOrganization(self):
        """Test UserCollectionReadOrganization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
