# coding: utf-8

"""
    Tripartie

    Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.

    The version of the OpenAPI document: 2.0.134
    Contact: noc@tripartie.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from tpdk.models.webhook_object import WebhookObject

class TestWebhookObject(unittest.TestCase):
    """WebhookObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookObject:
        """Test WebhookObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookObject`
        """
        model = WebhookObject()
        if include_optional:
            return WebhookObject(
                ulid = None,
                transaction = tpdk.models.transaction_read.Transaction-Read(
                    ulid = '', 
                    offer = tpdk.models.offer_read.Offer-Read(
                        ulid = '', 
                        public_url = 'https://marketplace.tld/offers/that-special-item-i-wish-to-sold', 
                        organization = tpdk.models.organization_read.Organization-Read(
                            name = '', 
                            website_url = '', 
                            custom_base_url = '', 
                            icon = tpdk.models.media_read.Media-Read(
                                public_url = 'https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg', ), 
                            logo = tpdk.models.media_read.Media-Read(
                                public_url = 'https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg', ), 
                            primary_color = '', 
                            secondary_color = '', 
                            accent_color = '', 
                            error_color = '', 
                            info_color = '', 
                            success_color = '', 
                            warning_color = '', 
                            direct_notification_toggle = True, 
                            persona_auth_portal_toggle = True, 
                            flat_rate_enabled = True, 
                            rate_commission_safe_checkout = 1.337, ), 
                        seller = tpdk.models.persona_read.Persona-Read(
                            id = 56, 
                            first_name = 'John', 
                            last_name = 'Doe', 
                            language = 'fr', 
                            email = 'john.doe@gmail.com', 
                            mobile_phone_number = '+33745214529', ), 
                        nature = 'physical_item', 
                        title = 'ASUS TUF X570-PLUS GAMING Motherboard', 
                        description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
                        unit_price = 125.54, 
                        currency_code = 'EUR', 
                        item_count = 1, 
                        condition = 'USED', 
                        medias = [
                            
                            ], ), 
                    buyer = tpdk.models.persona_read.Persona-Read(
                        id = 56, 
                        first_name = 'John', 
                        last_name = 'Doe', 
                        language = 'fr', 
                        email = 'john.doe@gmail.com', 
                        mobile_phone_number = '+33745214529', ), 
                    fees = 1.337, 
                    refundable_fees = True, 
                    metadata = [
                        tpdk.models.metadata_independent_write.Metadata-IndependentWrite(
                            key = 'External-ID', 
                            value = '54412', )
                        ], 
                    parcels = [
                        tpdk.models.parcel_read.Parcel-Read(
                            carrier = 'SwissPost', 
                            identifier = '8J001271466474', 
                            price = 4.88, 
                            refundable = True, 
                            currency = 'EUR', 
                            status = 'CREATED', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                status = CREATED,
                redirect_url = https://marketplace.tld/offers/that-special-item-i-wish-to-sold?from_dispute=true,
                item_count = 1,
                issue_type = NOT_AS_DESCRIBED,
                issue_in_description_type = WRONG_COLOUR,
                issue_mentioned_in_offer = None,
                issue_details = The item received have multiple impacts on the left side, this was not mentioned and I feel a bit sad. Although it is usable as-is, I expected it without flaws.,
                complainant_truthfulness_score = 100,
                seller_truthfulness_score = 100,
                complainant_stake = LOW,
                inferred_stake = LOW,
                recommended_solution = PARTIAL_REFUND_WITH_PARTIAL_RETURN,
                recommended_partial_refund_amount = 35,
                chosen_solution = PARTIAL_REFUND_WITH_PARTIAL_RETURN,
                chosen_partial_refund_amount = 40,
                counter_solution = PARTIAL_REFUND_WITH_PARTIAL_RETURN,
                counter_partial_refund_amount = 30,
                seller_notes = Unfortunately, I did not notice it, after thinking again, yes, you deserve a discount on that.,
                seller_rejection_reason = UNJUSTIFIED_REQUEST,
                complainant_approval = None,
                seller_approval = None,
                platform_solution = PARTIAL_REFUND_WITH_PARTIAL_RETURN,
                platform_partial_refund_amount = None,
                platform_approval = None,
                platform_actor_type = RULING,
                platform_reasoning = The buyer does not respect our terms of service.,
                arbitration_by = None,
                parcels = None,
                views = None,
                metadata = None,
                events = None,
                created_at = None,
                updated_at = None,
                view_count = None,
                status_expiration = None,
                awaited_party = BUYER,
                iri = None,
                message_count = 6,
                closed_in_favor_of = None,
                disbursed_by_buyer = None,
                max_refundable_for_buyer = None,
                id = None,
                first_name = John,
                last_name = Doe,
                language = fr,
                email = john.doe@gmail.com,
                mobile_phone_number = +33745214529,
                public_url = https://marketplace.tld/offers/that-special-item-i-wish-to-sold,
                organization = tpdk.models.organization_read.Organization-Read(
                    name = '', 
                    website_url = '', 
                    custom_base_url = '', 
                    icon = tpdk.models.media_read.Media-Read(
                        public_url = 'https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg', ), 
                    logo = tpdk.models.media_read.Media-Read(
                        public_url = 'https://cdn.tripartie.app/b15e64db-fbd2-442b-afee-69ee45e2959b.jpg', ), 
                    primary_color = '', 
                    secondary_color = '', 
                    accent_color = '', 
                    error_color = '', 
                    info_color = '', 
                    success_color = '', 
                    warning_color = '', 
                    direct_notification_toggle = True, 
                    persona_auth_portal_toggle = True, 
                    flat_rate_enabled = True, 
                    rate_commission_safe_checkout = 1.337, ),
                seller = tpdk.models.persona_read.Persona-Read(
                    id = 56, 
                    first_name = 'John', 
                    last_name = 'Doe', 
                    language = 'fr', 
                    email = 'john.doe@gmail.com', 
                    mobile_phone_number = '+33745214529', ),
                nature = physical_item,
                title = ASUS TUF X570-PLUS GAMING Motherboard,
                description = Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.,
                unit_price = 125.54,
                currency_code = EUR,
                condition = USED,
                medias = None
            )
        else:
            return WebhookObject(
                ulid = None,
                status = CREATED,
                complainant_truthfulness_score = 100,
                seller_truthfulness_score = 100,
                parcels = None,
                views = None,
                metadata = None,
                seller = tpdk.models.persona_read.Persona-Read(
                    id = 56, 
                    first_name = 'John', 
                    last_name = 'Doe', 
                    language = 'fr', 
                    email = 'john.doe@gmail.com', 
                    mobile_phone_number = '+33745214529', ),
                nature = physical_item,
                medias = None,
        )
        """

    def testWebhookObject(self):
        """Test WebhookObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
