/*
 * Resolution Center
 * Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution.
 *
 * The version of the OpenAPI document: 2.0.208
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.tpdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.tpdk.model.DisputeMediaRead;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DisputeOrganizationRead
 */
public class DisputeOrganizationReadTest {
    private final DisputeOrganizationRead model = new DisputeOrganizationRead();

    /**
     * Model tests for DisputeOrganizationRead
     */
    @Test
    public void testDisputeOrganizationRead() {
        // TODO: test DisputeOrganizationRead
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    public void websiteUrlTest() {
        // TODO: test websiteUrl
    }

    /**
     * Test the property 'customBaseUrl'
     */
    @Test
    public void customBaseUrlTest() {
        // TODO: test customBaseUrl
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'primaryColor'
     */
    @Test
    public void primaryColorTest() {
        // TODO: test primaryColor
    }

    /**
     * Test the property 'directNotificationToggle'
     */
    @Test
    public void directNotificationToggleTest() {
        // TODO: test directNotificationToggle
    }

    /**
     * Test the property 'personaAuthPortalToggle'
     */
    @Test
    public void personaAuthPortalToggleTest() {
        // TODO: test personaAuthPortalToggle
    }

    /**
     * Test the property 'counterProposalToggle'
     */
    @Test
    public void counterProposalToggleTest() {
        // TODO: test counterProposalToggle
    }

    /**
     * Test the property 'flatRateEnabled'
     */
    @Test
    public void flatRateEnabledTest() {
        // TODO: test flatRateEnabled
    }

}
