/*
 * Tripartie
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.199
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.tpdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tripartie.tpdk.model.OfferMetadataWrite;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OfferWrite
 */
public class OfferWriteTest {
    private final OfferWrite model = new OfferWrite();

    /**
     * Model tests for OfferWrite
     */
    @Test
    public void testOfferWrite() {
        // TODO: test OfferWrite
    }

    /**
     * Test the property 'publicUrl'
     */
    @Test
    public void publicUrlTest() {
        // TODO: test publicUrl
    }

    /**
     * Test the property 'enforcePersonaAuth'
     */
    @Test
    public void enforcePersonaAuthTest() {
        // TODO: test enforcePersonaAuth
    }

    /**
     * Test the property 'overrideRateCommissionSafeCheckout'
     */
    @Test
    public void overrideRateCommissionSafeCheckoutTest() {
        // TODO: test overrideRateCommissionSafeCheckout
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'weightInGram'
     */
    @Test
    public void weightInGramTest() {
        // TODO: test weightInGram
    }

    /**
     * Test the property 'shippingAllowed'
     */
    @Test
    public void shippingAllowedTest() {
        // TODO: test shippingAllowed
    }

    /**
     * Test the property 'handDeliveryAllowed'
     */
    @Test
    public void handDeliveryAllowedTest() {
        // TODO: test handDeliveryAllowed
    }

    /**
     * Test the property 'shippingCarriers'
     */
    @Test
    public void shippingCarriersTest() {
        // TODO: test shippingCarriers
    }

    /**
     * Test the property 'eanCode'
     */
    @Test
    public void eanCodeTest() {
        // TODO: test eanCode
    }

    /**
     * Test the property 'canBeSoldSeparately'
     */
    @Test
    public void canBeSoldSeparatelyTest() {
        // TODO: test canBeSoldSeparately
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
