/*
 * Tripartie
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.178
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tripartie.tpdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PersonaExternalAuth
 */
public class PersonaExternalAuthTest {
    private final PersonaExternalAuth model = new PersonaExternalAuth();

    /**
     * Model tests for PersonaExternalAuth
     */
    @Test
    public void testPersonaExternalAuth() {
        // TODO: test PersonaExternalAuth
    }

    /**
     * Test the property 'captcha'
     */
    @Test
    public void captchaTest() {
        // TODO: test captcha
    }

    /**
     * Test the property 'targetUrl'
     */
    @Test
    public void targetUrlTest() {
        // TODO: test targetUrl
    }

    /**
     * Test the property 'plainPassword'
     */
    @Test
    public void plainPasswordTest() {
        // TODO: test plainPassword
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    public void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

}
