/*
 * Tripartie
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.177
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.tripartie.tpdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserUserPasswordUpdate
 */
public class UserUserPasswordUpdateTest {
    private final UserUserPasswordUpdate model = new UserUserPasswordUpdate();

    /**
     * Model tests for UserUserPasswordUpdate
     */
    @Test
    public void testUserUserPasswordUpdate() {
        // TODO: test UserUserPasswordUpdate
    }

    /**
     * Test the property 'plainPassword'
     */
    @Test
    public void plainPasswordTest() {
        // TODO: test plainPassword
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

}
