/*
 * Tripartie
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.177
 * Contact: noc@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.tripartie.tpdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.tripartie.tpdk.model.View;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for User
 */
public class UserTest {
    private final User model = new User();

    /**
     * Model tests for User
     */
    @Test
    public void testUser() {
        // TODO: test User
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'captcha'
     */
    @Test
    public void captchaTest() {
        // TODO: test captcha
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'publicName'
     */
    @Test
    public void publicNameTest() {
        // TODO: test publicName
    }

    /**
     * Test the property 'roleInCompany'
     */
    @Test
    public void roleInCompanyTest() {
        // TODO: test roleInCompany
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    public void birthdayTest() {
        // TODO: test birthday
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'invitedRole'
     */
    @Test
    public void invitedRoleTest() {
        // TODO: test invitedRole
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'plainPassword'
     */
    @Test
    public void plainPasswordTest() {
        // TODO: test plainPassword
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

    /**
     * Test the property 'totpSecret'
     */
    @Test
    public void totpSecretTest() {
        // TODO: test totpSecret
    }

    /**
     * Test the property 'totpUri'
     */
    @Test
    public void totpUriTest() {
        // TODO: test totpUri
    }

    /**
     * Test the property 'totpEnabled'
     */
    @Test
    public void totpEnabledTest() {
        // TODO: test totpEnabled
    }

    /**
     * Test the property 'totpChallenge'
     */
    @Test
    public void totpChallengeTest() {
        // TODO: test totpChallenge
    }

    /**
     * Test the property 'intlPhoneNumber'
     */
    @Test
    public void intlPhoneNumberTest() {
        // TODO: test intlPhoneNumber
    }

    /**
     * Test the property 'originCountry'
     */
    @Test
    public void originCountryTest() {
        // TODO: test originCountry
    }

    /**
     * Test the property 'preferredLanguage'
     */
    @Test
    public void preferredLanguageTest() {
        // TODO: test preferredLanguage
    }

    /**
     * Test the property 'lastSuccessfulLogIn'
     */
    @Test
    public void lastSuccessfulLogInTest() {
        // TODO: test lastSuccessfulLogIn
    }

    /**
     * Test the property 'emailVerificationCode'
     */
    @Test
    public void emailVerificationCodeTest() {
        // TODO: test emailVerificationCode
    }

    /**
     * Test the property 'emailVerificationInput'
     */
    @Test
    public void emailVerificationInputTest() {
        // TODO: test emailVerificationInput
    }

    /**
     * Test the property 'phoneVerificationCode'
     */
    @Test
    public void phoneVerificationCodeTest() {
        // TODO: test phoneVerificationCode
    }

    /**
     * Test the property 'phoneVerificationInput'
     */
    @Test
    public void phoneVerificationInputTest() {
        // TODO: test phoneVerificationInput
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'medias'
     */
    @Test
    public void mediasTest() {
        // TODO: test medias
    }

    /**
     * Test the property 'views'
     */
    @Test
    public void viewsTest() {
        // TODO: test views
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'consentMailNotification'
     */
    @Test
    public void consentMailNotificationTest() {
        // TODO: test consentMailNotification
    }

    /**
     * Test the property 'consentMailAds'
     */
    @Test
    public void consentMailAdsTest() {
        // TODO: test consentMailAds
    }

    /**
     * Test the property 'lockdown'
     */
    @Test
    public void lockdownTest() {
        // TODO: test lockdown
    }

    /**
     * Test the property 'keys'
     */
    @Test
    public void keysTest() {
        // TODO: test keys
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'impersonatedOrganization'
     */
    @Test
    public void impersonatedOrganizationTest() {
        // TODO: test impersonatedOrganization
    }

    /**
     * Test the property 'iri'
     */
    @Test
    public void iriTest() {
        // TODO: test iri
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'salt'
     */
    @Test
    public void saltTest() {
        // TODO: test salt
    }

    /**
     * Test the property 'userIdentifier'
     */
    @Test
    public void userIdentifierTest() {
        // TODO: test userIdentifier
    }

    /**
     * Test the property 'impersonatingOrganization'
     */
    @Test
    public void impersonatingOrganizationTest() {
        // TODO: test impersonatingOrganization
    }

    /**
     * Test the property '_2fa'
     */
    @Test
    public void _2faTest() {
        // TODO: test _2fa
    }

}
